### ISSUE TITLE
Barclays - token endpoint cannot be resolved

### ISSUE THREAD

**Issue by oliver-hohn** [openbankingspace/tpp-issues#31] opened 2018-08-09 12:31 UTC
DNS resolution is failing when attempting to create a Client Credentials Grant. We suspect that this is not limited to only creating Client Credentials, but to the `token` sub-domain.

Example request:
```
POST https://token.tiaa.barclays.com/as/token.oauth2
```

and example error:
```
SocketError
getaddrinfo: nodename nor servname provided, or not known (token.tiaa.barclays.com:443)
```

## Impact

Very High. With the `token` sub-domain being down it is not possible to initiate a Barclays Open Banking journey, and thus preventing users from sharing their account information.

**Comment by tobypinder** [comment] 2018-08-09 13:01
Upgraded to critical - this renders open banking completely inaccessible across the entire platform.

**Comment by o6uoq** [comment] 2018-08-09 13:41
It looks like Barclays blew away the DNS records for everything on `*.tiaa.barclays.com`:

```
$ dig @A1-71.AKAM.NET +nocmd +noall +answer tiaa.barclays.com any
$
```
🤷🏻‍♂️

**Comment by tobypinder** [comment] 2018-08-09 19:17
Token EP appears to be up now but the authorization server presents the PSU with `Error 500: javax.servlet.ServletException: SRVE0207E: Uncaught initialization exception created by servlet`.

Impact to TPPs is the same.

**Comment by oliver-hohn** [comment] 2018-08-10 08:51
The authorization server issues mentioned above seemed to have been fixed now, and a full end-to-end journey (user consent, token swap, and data fetching) is now possible again.

**Comment by tobypinder** [comment] 2018-08-10 09:31
As the downtime is resolved I am closing this issue, but we will provide updates if more information about the downtime window is provided to us.

**Closed by tobypinder** 2018-08-10 09:31 UTC
Labels: aspsp:barclays, env:live, issue:down, priority:critical, type:auth

**Comment by tobypinder** [comment] 2018-08-10 11:32
Barclays informed us the downtime was caused by a failure in a service discovery module's TLS configuration, which cascaded to DNS unavailability.

**Comment by tobypinder** [comment] 2018-08-14 13:33
OBIE asked Barclays for a reason for recent downtime and have been advised they are unable to share due to security reasons.
